# Generated by Django 3.2 on 2021-07-04 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('monedapago', models.CharField(max_length=15)),
                ('rut_id', models.CharField(max_length=12)),
                ('imagen', models.ImageField(null=True, upload_to='logo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca')),
            ],
        ),
    ]
