# Generated by Django 3.2 on 2021-07-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_contacto', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='monedapago',
            field=models.IntegerField(choices=[[0, 'Peso Chileno'], [1, 'Unidad de Fomento'], [2, 'Dolar Americano'], [3, 'Dolar Canadiense'], [4, 'Euro'], [5, 'Peseta'], [6, 'Chelines']]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pais',
            field=models.IntegerField(choices=[[0, 'Chile'], [1, 'Argentina'], [2, 'Estados Unidos'], [3, 'Canada'], [4, 'Reino Unido'], [5, 'Inglaterra'], [6, 'Otro']]),
        ),
    ]
