# Generated by Django 3.2 on 2021-07-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210703_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='logo_empresa',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='monedapago',
            new_name='moneda_pago',
        ),
        migrations.AddField(
            model_name='producto',
            name='comuna',
            field=models.CharField(default='', max_length=30),
        ),
    ]
