# Generated by Django 3.2 on 2021-07-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_logo_empresa_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='moneda_pago',
            field=models.IntegerField(choices=[[0, '$ CLP'], [1, '$ CUF'], [2, 'US$ USD'], [3, '¥ Yen'], [4, '€ EUR'], [5, '£ GBP '], [6, 'OTRO']]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pais',
            field=models.IntegerField(choices=[[0, 'Chile'], [1, 'Argentina'], [2, 'Estados Unidos'], [3, 'China'], [4, 'Reino Unido'], [5, 'Inglaterra'], [6, 'Japon'], [7, 'Otro']]),
        ),
    ]
