# Generated by Django 3.2 on 2021-07-07 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210704_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='tipo',
            new_name='Tipo_Proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='password',
        ),
    ]
