# Generated by Django 3.2 on 2021-07-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210706_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='producto',
            name='password',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
